global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: windows_exporter
    static_configs:
      - targets:
          - 'localhost:9182'
  - job_name: ihs
    static_configs:
      - targets:
          - 'localhost:5000'
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']
