{
 "title": "Alertmanager",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [
  "alertmanager",
  "prometheus",
  "alerting"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(alertmanager_build_info)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of instances",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(alertmanager_build_info{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Instance versions and up time",
   "type": "table-old",
   "description": "Table containing list of Alertmanager instances showing it's version, up time, last reload time and if it was successful.",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "time() - (alertmanager_build_info{instance=~\"$instance\"} * on (instance, cluster) group_left process_start_time_seconds{instance=~\"$instance\"})"
    },
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{instance=~\"$instance\"}"
    },
    {
     "expr": "alertmanager_config_last_reload_successful{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "singlestat",
   "description": "Number of peers in the Alertmanager cluster.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_cluster_members{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of active alerts",
   "type": "singlestat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of suppressed alerts",
   "type": "singlestat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"suppressed\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Number of active silences",
   "type": "singlestat",
   "description": "Current number of active silences.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_silences{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Notifications sent from $instance",
   "type": "graph",
   "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_total{instance=~\"$instance\"}[$__interval])) by (integration)",
     "legendFormat": "{{ integration}}"
    },
    {
     "expr": "sum(increase(alertmanager_notifications_failed_total{instance=~\"$instance\"}[$__interval])) by (integration)",
     "legendFormat": "Failed {{ integration }}"
    }
   ]
  },
  {
   "title": "Notification durations per integration on $instance",
   "type": "graph",
   "description": "Duration of notification sends in 0.99 and 0.9 quantiles per integration.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "repeat": "instance",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.9,rate(alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"}[$__interval]))) by (integration)",
     "legendFormat": "0.9q {{ integration }}"
    },
    {
     "expr": "sum(histogram_quantile(0.99,rate(alertmanager_notification_latency_seconds_bucket{instance=~\"$instance\"}[$__interval]))) by (integration)",
     "legendFormat": "0.99q  {{ integration }}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active alerts in $instance",
   "type": "graph",
   "description": "Number of alerts by state such as `active`, `suppressed` etc.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{instance=~\"$instance\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Received alerts by status for $instance",
   "type": "graph",
   "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alertmanager_alerts_received_total{instance=~\"$instance\"}[$__interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}