{
 "title": "IHS - BillRun",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Rate of Exceptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ihs_bill_run_service_errors_total[10m])",
     "legendFormat": "{{exceptionType}}"
    }
   ]
  },
  {
   "title": "# of exceptions in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ihs_bill_run_service_errors_total[24h]))"
    }
   ]
  },
  {
   "title": "HTTP Request Durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{controller=\"BillRun\"}[5m])) by (le)"
    }
   ]
  },
  {
   "title": "HandleBillRun Duration Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ihs_bill_run_operation_durations{method=\"handle_bill_run\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "HandleBillRun avg. duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ihs_bill_run_operation_durations_count[10m])) / sum(rate(ihs_bill_run_operation_durations_sum[10m]))"
    }
   ]
  },
  {
   "title": "Rate of HTTP Requests Received",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_received_total{controller=\"BillRun\"}[10m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "GetBillRun Duration Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ihs_bill_run_service_operation_durations",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "GetBillRun avg. duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ihs_bill_run_service_operation_durations_count[10m])) / sum(rate(ihs_bill_run_service_operation_durations_sum[10m]))"
    }
   ]
  }
 ]
}