{
 "title": "IHS - AsyncWorker",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ihs_AsyncWorker_Status" }
   ]
  },
  {
   "title": "# of Items in current queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ihs_AsyncWorker_ItemsInQueue" }
   ]
  },
  {
   "title": "HTTP Request Durations",
   "type": "heatmap",
   "description": "Shows the number of HTTP requests that fall into each duration bucket. ",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{controller=\"AsyncWorker\"}[5m])) by (le)"
    }
   ]
  },
  {
   "title": "Rate of Exceptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ihs_async_worker_errors_total[10m])",
     "legendFormat": "{{exceptionType}}"
    }
   ]
  },
  {
   "title": "# of exceptions in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ihs_async_worker_errors_total[24h]))"
    }
   ]
  },
  {
   "title": "Rate of HTTP Requests Received",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_received_total{controller=\"AsyncWorker\"}[10m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "ProcessWorkItem Duration Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ihs_async_worker_process_work_item_duration_seconds",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "ProcessWorkItem avg. duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ihs_async_worker_process_work_item_duration_seconds_count[10m])) / sum(rate(ihs_async_worker_process_work_item_duration_seconds_sum[10m]))"
    }
   ]
  }
 ]
}