{
 "title": "IHS - InvoiceHandling",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Rate of Exceptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ihs_invoice_handling_service_errors_total[10m])"
    }
   ]
  },
  {
   "title": "# of exceptions in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ihs_invoice_handling_service_errors_total[24h]))"
    }
   ]
  },
  {
   "title": "HTTP Request Durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{controller=\"Invoice\"}[5m])) by (le)"
    }
   ]
  },
  {
   "title": "GetInvoice Duration Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ihs_invoice_handling_service_operation_durations{method=\"get_invoice\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "GetInvoice avg. duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ihs_invoice_handling_service_operation_durations_count[10m])) / sum(rate(ihs_invoice_handling_service_operation_durations_sum[10m]))"
    }
   ]
  },
  {
   "title": "Rate of HTTP Requests Received",
   "type": "graph",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_received_total{controller=\"Invoice\"}[10m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Positive Balance Invoices Handled",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "invoice_logic_positive_balance_invoices_handled_total"
    }
   ]
  },
  {
   "title": "Zero Balance Invoices Handled",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "invoice_logic_zero_balance_invoices_handled_total"
    }
   ]
  },
  {
   "title": "Negative Balance Invoices Handled",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "invoice_logic_negative_balance_invoices_handled_total"
    }
   ]
  },
  {
   "title": "Total emails sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "invoice_handling_service_emails_sent_total"
    }
   ]
  }
 ]
}